
  // JavaScript function to show the modal box
  function openModal(modalId) {
    const modal = document.getElementById(modalId);
    modal.style.display = "block";
  }

  // Close the modal box when the user clicks on the close button or outside of the modal box
  const modals = document.querySelectorAll('.modal');
  modals.forEach((modal) => {
    const closeBtn = modal.querySelector('.close');
    window.addEventListener('click', (event) => {
      if (event.target === modal || event.target === closeBtn) {
        modal.style.display = 'none';
      }
    });

    closeBtn.addEventListener("click", function() {
      // Get the parent modal element of the clicked close button
      var modal = this.parentElement.parentElement;
      // Hide the modal by setting its display property to none
      modal.style.display = "none";
    });
  });





  (() => {
  //If you want to add more images, add the link name and URL image URL in the array list below.
    const images_list = [
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_bac60bacbf5da8945103648c08d27d5e202444ca.1920x1080.jpg?t=1671485009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_66b553f4c209476d3e4ce25fa4714002cc914c4f.1920x1080.jpg?t=1671485009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_668dafe477743f8b50b818d5bbfcec669e9ba93e.1920x1080.jpg?t=1671485009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_d1a8f5a69155c3186c65d1da90491fcfd43663d9.1920x1080.jpg?t=1671485009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1174180/ss_4ce07ae360b166f0f650e9a895a3b4b7bf15e34f.1920x1080.jpg?t=1671485009",
      "alt": "",
      "name": "",
      "link": ""
  }
    ];
  
  // generated by https://www.html-code-generator.com/html/image-slideshow-generator
    let slider_id = document.querySelector("#hcg-slider-6");
  
    // append all images
    let dots_div = "";
    let images_div = "";
    for (let i = 0; i < images_list.length; i++) {
      // if no link without href="" tag
      let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
      images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
              '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
              '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
             '</a>';
    }
    slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
    let slide_index = 0;
  
    const images = slider_id.querySelectorAll(".hcg-slides");
    const showSlides = () => {
      if (slide_index > images.length-1) {
        slide_index = 0;
      }
      if (slide_index < 0) {
        slide_index = images.length-1;
      }
      for (let i = 0; i < images.length; i++) {
        images[i].style.display = "none";
        if (i == slide_index) {
          images[i].style.display = "flex";
        }
      }
    }
  
    // auto play
    setInterval(() => {
      slide_index++;
      showSlides();
    }, 7000);
  
  })();





  (() => {
  //If you want to add more images, add the link name and URL image URL in the array list below.
    const images_list = [
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/ss_c836f889d696fa2b81d5fe9f20f75dd925c1b499.1920x1080.jpg?t=1661971606",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/ss_ebd31ded4723e991446ededa9e65c980f988567d.1920x1080.jpg?t=1661971606",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/ss_7e6a2148321c8024285e3924903d8897cac95358.1920x1080.jpg?t=1661971606",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/ss_9cdf861c8ac2d7fa7e1f2a88673032bc3a6c6114.1920x1080.jpg?t=1661971606",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/782330/ss_af3b43c4be0029b52ceefaf55ebe1918e2cb3471.1920x1080.jpg?t=1661971606",
      "alt": "",
      "name": "",
      "link": ""
  }
    ];
  
  // generated by https://www.html-code-generator.com/html/image-slideshow-generator
    let slider_id = document.querySelector("#hcg-slider-5");
  
    // append all images
    let dots_div = "";
    let images_div = "";
    for (let i = 0; i < images_list.length; i++) {
      // if no link without href="" tag
      let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
      images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
              '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
              '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
             '</a>';
    }
    slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
    let slide_index = 0;
  
    const images = slider_id.querySelectorAll(".hcg-slides");
    const showSlides = () => {
      if (slide_index > images.length-1) {
        slide_index = 0;
      }
      if (slide_index < 0) {
        slide_index = images.length-1;
      }
      for (let i = 0; i < images.length; i++) {
        images[i].style.display = "none";
        if (i == slide_index) {
          images[i].style.display = "flex";
        }
      }
    }
  
    // auto play
    setInterval(() => {
      slide_index++;
      showSlides();
    }, 7000);
  
  })();






  (() => {
  //If you want to add more images, add the link name and URL image URL in the array list below.
    const images_list = [
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/107410/ss_d6ac5531165a238499e1bf7ad71ee23dcfcbcf78.1920x1080.jpg?t=1677682009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/107410/ss_d705d125b0bf4e8d934c8743ef1a26e851fe6cf4.1920x1080.jpg?t=1677682009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/107410/ss_de3d649293bf035ae7c1d9cf35235ea2ec36beee.1920x1080.jpg?t=1677682009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/107410/ss_d8b72126ea6b20eabf618bec392f8f5c3f29cc42.1920x1080.jpg?t=1677682009",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/107410/ss_e0f3abf9ac5db034005a00cf6b1adfbd611d2a2f.1920x1080.jpg?t=1677682009",
      "alt": "",
      "name": "",
      "link": ""
  }
    ];
  
  // generated by https://www.html-code-generator.com/html/image-slideshow-generator
    let slider_id = document.querySelector("#hcg-slider-4");
  
    // append all images
    let dots_div = "";
    let images_div = "";
    for (let i = 0; i < images_list.length; i++) {
      // if no link without href="" tag
      let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
      images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
              '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
              '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
             '</a>';
    }
    slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
    let slide_index = 0;
  
    const images = slider_id.querySelectorAll(".hcg-slides");
    const showSlides = () => {
      if (slide_index > images.length-1) {
        slide_index = 0;
      }
      if (slide_index < 0) {
        slide_index = images.length-1;
      }
      for (let i = 0; i < images.length; i++) {
        images[i].style.display = "none";
        if (i == slide_index) {
          images[i].style.display = "flex";
        }
      }
    }
  
    // auto play
    setInterval(() => {
      slide_index++;
      showSlides();
    }, 7000);
  
  })();





    (() => {
    //If you want to add more images, add the link name and URL image URL in the array list below.
      const images_list = [
    {
        "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1151700/ss_5182793aff1a31649a83f41583d44e61bca29982.1920x1080.jpg?t=1666690957",
        "alt": "",
        "name": "",
        "link": ""
    },
    {
        "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/221100/ss_0de6d2e7f3b5348d69bb09d60624c78e13f0c8d7.1920x1080.jpg?t=1674143992",
        "alt": "",
        "name": "",
        "link": ""
    },
    {
        "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1151700/ss_c84806c1b373dfc7a00a6d066d1c830aaf059b09.1920x1080.jpg?t=1666690957",
        "alt": "",
        "name": "",
        "link": ""
    },
    {
        "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1151700/ss_bbdec56e6704e3e4390b49e7351fc599f2b75a14.1920x1080.jpg?t=1666690957",
        "alt": "",
        "name": "",
        "link": ""
    },
    {
        "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/221100/ss_7892d0526421d31a3d1eebb6cf919118fcfb2ca5.1920x1080.jpg?t=1674143992",
        "alt": "",
        "name": "",
        "link": ""
    }
      ];
    
    // generated by https://www.html-code-generator.com/html/image-slideshow-generator
      let slider_id = document.querySelector("#hcg-slider-3");
    
      // append all images
      let dots_div = "";
      let images_div = "";
      for (let i = 0; i < images_list.length; i++) {
        // if no link without href="" tag
        let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
        images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
                '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
                '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
               '</a>';
      }
      slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
      let slide_index = 0;
    
      const images = slider_id.querySelectorAll(".hcg-slides");
      const showSlides = () => {
        if (slide_index > images.length-1) {
          slide_index = 0;
        }
        if (slide_index < 0) {
          slide_index = images.length-1;
        }
        for (let i = 0; i < images.length; i++) {
          images[i].style.display = "none";
          if (i == slide_index) {
            images[i].style.display = "flex";
          }
        }
      }
    
      // auto play
      setInterval(() => {
        slide_index++;
        showSlides();
      }, 7000);
    
    })();




  (() => {
  //If you want to add more images, add the link name and URL image URL in the array list below.
    const images_list = [
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/ss_0c20c45d2e00feae5b9edfb6526662cc3c669164.1920x1080.jpg?t=1664070673",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/ss_0569f81cafd8b18870d6d5bc296ad557f5576067.1920x1080.jpg?t=1664070673",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/ss_431ae8bbb5ff7e7cc6740e49c584e1015c6ea8e1.1920x1080.jpg?t=1664070673",
      "alt": "",
      "name": "",
      "link": ""
  },

  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/ss_73a21e43ec44cac9aab41d122a284582d194d352.1920x1080.jpg?t=1664070673",
      "alt": "",
      "name": "",
      "link": ""
  }

  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1238810/ss_818562302f3d6fdcab1689e5618a52e4b53a71f6.1920x1080.jpg?t=1664070673",
      "alt": "",
      "name": "",
      "link": ""
  }
    ];
  
  // generated by https://www.html-code-generator.com/html/image-slideshow-generator
    let slider_id = document.querySelector("#hcg-slider-2");
  
    // append all images
    let dots_div = "";
    let images_div = "";
    for (let i = 0; i < images_list.length; i++) {
      // if no link without href="" tag
      let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
      images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
              '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
              '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
             '</a>';
    }
    slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
    let slide_index = 0;
  
    const images = slider_id.querySelectorAll(".hcg-slides");
    const showSlides = () => {
      if (slide_index > images.length-1) {
        slide_index = 0;
      }
      if (slide_index < 0) {
        slide_index = images.length-1;
      }
      for (let i = 0; i < images.length; i++) {
        images[i].style.display = "none";
        if (i == slide_index) {
          images[i].style.display = "flex";
        }
      }
    }
  
    // auto play
    setInterval(() => {
      slide_index++;
      showSlides();
    }, 7000);
  
  })();






  (() => {
  //If you want to add more images, add the link name and URL image URL in the array list below.
    const images_list = [
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/ss_da11f26c8fec6def6e235786e11b868eb8b115ef.1920x1080.jpg?t=1681315823",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/ss_669067a108c25b5a1f62d25f9fbca1739ecca1b7.1920x1080.jpg?t=1681315823",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/ss_69bdea4d9d5ad715d3e0e26dcaa537e99a951128.1920x1080.jpg?t=1681315823",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/ss_8de4a0d335005618ea9899b4ef5e2014343c4b3a.1920x1080.jpg?t=1681315823",
      "alt": "",
      "name": "",
      "link": ""
  },
  {
      "url": "https://cdn.cloudflare.steamstatic.com/steam/apps/1938090/ss_6b75b48844279eadc00918b7420f0c52703cb256.1920x1080.jpg?t=1681315823",
      "alt": "",
      "name": "",
      "link": ""
  }
    ];
  
  // generated by https://www.html-code-generator.com/html/image-slideshow-generator
    let slider_id = document.querySelector("#hcg-slider-1");
  
    // append all images
    let dots_div = "";
    let images_div = "";
    for (let i = 0; i < images_list.length; i++) {
      // if no link without href="" tag
      let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
      images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
              '<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
              '<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
              '<span class="hcg-slide-text">'+images_list[i].name+'</span>'+
             '</a>';
    }
    slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
    let slide_index = 0;
  
    const images = slider_id.querySelectorAll(".hcg-slides");
    const showSlides = () => {
      if (slide_index > images.length-1) {
        slide_index = 0;
      }
      if (slide_index < 0) {
        slide_index = images.length-1;
      }
      for (let i = 0; i < images.length; i++) {
        images[i].style.display = "none";
        if (i == slide_index) {
          images[i].style.display = "flex";
        }
      }
    }
  
    // auto play
    setInterval(() => {
      slide_index++;
      showSlides();
    }, 7000);
  
  })();
